spring:
  cloud:
    nacos:
      discovery:
        metadata:
          context-path: ${server.servlet.context-path}

---
spring:
  config:
    activate:
      on-profile: dev
  # rabbitmq
  rabbitmq:
    host: data.luopc.com
    port: 5672
    username: dev
    password: Robin2023
    virtualHost: dev
    publisher-returns: true

---
spring:
  config:
    activate:
      on-profile: uat
  # rabbitmq
  rabbitmq:
    host: data.luopc.com
    port: 5672
    username: uat
    password: Robin2023
    virtualHost: uat